[build]
  publish = "build/web"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
  FLUTTER_CHANNEL = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
